# Generated by Django 4.1 on 2023-02-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairmanapp', '0002_societymember_family_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='societymember',
            name='pic',
            field=models.FileField(default='media/minion dracula.png', upload_to='media/upload'),
        ),
    ]
