# Generated by Django 4.1 on 2023-02-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairmanapp', '0004_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='societymember',
            name='gender',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='societymember',
            name='Family_members',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='societymember',
            name='House_Owner',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='societymember',
            name='House_no',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='societymember',
            name='Vehical_details',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='societymember',
            name='blood_group',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='societymember',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='societymember',
            name='contact_no',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='societymember',
            name='firstname',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='societymember',
            name='lastname',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='societymember',
            name='occupation',
            field=models.CharField(default='', max_length=100),
        ),
    ]
