# Generated by Django 4.1 on 2023-02-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairmanapp', '0005_societymember_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('others', 'Others'), ('male', 'Male'), ('female', 'Female')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='pro_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
