# Generated by Django 4.1 on 2023-03-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairmanapp', '0006_user_gender_user_pro_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pro_pic',
            field=models.ImageField(null=True, upload_to='media/upload'),
        ),
    ]
